Repository clearlinux/clear-linux-documentation, pull requests merged in 2019-12, with the labels that each got.

#945 dpdk.rst: Fixes Figure caption indent (see pr 896)
  source/guides/network/dpdk.rst
Labels: P3

#946 Updated to mount the /boot partition
  source/guides/maintenance/fix-broken-install.rst
Labels: P2, community

#951 Simplify section "Boot a live desktop image to fix..." in fix-broken-install
  source/guides/maintenance/fix-broken-install.rst
Labels: P2

#950 Combine two VMWare guides into one: vmw-player.
  source/_figures/vmw-player/vmw-player-01.png
  source/_figures/vmw-player/vmw-player-02.png
  source/_figures/vmw-player/vmw-player-03.png
  source/_figures/vmw-player/vmw-player-04.png
  source/_figures/vmw-player/vmw-player-05.png
  source/_figures/vmw-player/vmw-player-06.png
  source/_figures/vmw-player/vmw-player-07.png
  source/_figures/vmw-player/vmw-player-08.png
  source/_figures/vmw-player/vmw-player-09.png
  source/_figures/vmw-player/vmw-player-10.png
  source/_figures/vmw-player/vmw-player-11.png
  source/_figures/vmw-player/vmw-player-17.png
  source/_figures/vmw-player/vmw-player-preconf-01.png
  source/_figures/vmw-player/vmw-player-preconf-02.png
  source/_figures/vmw-player/vmw-player-preconf-03.png
  source/_figures/vmw-player/vmw-player-preconf-04.png
  source/_figures/vmw-player/vmw-player-preconf-05.png
  source/_figures/vmw-player/vmw-player-preconf-06.png
  source/_figures/vmw-player/vmw-player-preconf-07.png
  source/_figures/vmw-player/vmw-player-preconf-08.png
  source/_figures/vmw-player/vmw-player-preconf-09.png
  source/_figures/vmw-player/vmw-player-preconf-12.png
  source/_figures/vmw-player/vmw-player-preconf-13.png
  source/_figures/vmw-player/vmw-player-preconf-14.png
  source/_figures/vmw-player/vmw-player-preconf-15.png
  source/_figures/vmw-player/vmw-player-preconf-16.png
  source/get-started/virtual-machine-install/figures/vmw-player-preconf/vmw-player-preconf-15.png
  source/get-started/virtual-machine-install/figures/vmw-player/vmw-player-02.png
  source/get-started/virtual-machine-install/vmw-player-preconf.rst
  source/get-started/virtual-machine-install/vmw-player.rst
  source/get-started/virtual-machine-install/vmware-esxi-install-cl.rst
  source/get-started/virtual-machine-install/vmware-esxi-preconfigured-cl-image.rst
Labels: P3

#942 parallels.rst: Fixes Figure caption indent Closes #896
  source/get-started/virtual-machine-install/parallels.rst
Labels: P3

#947 Add improved role descriptions and bundles to developer-workstation
  source/guides/maintenance/developer-workstation.rst
Labels: P2

#956 Windows command sha512 -> SHA512
  source/guides/maintenance/download-verify-decompress.rst
Labels: P2, community

#944 vnc.rst: corrected figure numbering to be sequential
  source/guides/network/vnc.rst
Labels: P3

#952 Deploy Clear to DigitalOcean guide.
  source/_figures/digitalocean/01-digitalocean-original.png
  source/_figures/digitalocean/01-digitalocean.png
  source/_figures/digitalocean/02-digitalocean-original.png
  source/_figures/digitalocean/02-digitalocean.png
  source/_figures/digitalocean/03-digitalocean-original.png
  source/_figures/digitalocean/03-digitalocean.png
  source/_figures/digitalocean/04-digitalocean-original.png
  source/_figures/digitalocean/04-digitalocean.png
  source/_figures/digitalocean/05-digitalocean-original.png
  source/_figures/digitalocean/05-digitalocean.png
  source/_figures/digitalocean/06-digitalocean-original.png
  source/_figures/digitalocean/06-digitalocean.png
  source/_figures/digitalocean/07-digitalocean-original.png
  source/_figures/digitalocean/07-digitalocean.png
  source/_figures/digitalocean/08-digitalocean-original.png
  source/_figures/digitalocean/08-digitalocean.png
  source/_figures/digitalocean/09-digitalocean-original.png
  source/_figures/digitalocean/09-digitalocean.png
  source/_figures/digitalocean/10-digitalocean-original.png
  source/_figures/digitalocean/10-digitalocean.png
  source/_figures/digitalocean/11-digitalocean-original.png
  source/_figures/digitalocean/11-digitalocean.png
  source/_figures/digitalocean/AA-digitalocean-original-extra.png
  source/_figures/digitalocean/BB-digitalocean-original-extra.png
  source/_figures/digitalocean/CC-digitalocean-original-extra.png
  source/_figures/digitalocean/Readme.txt
  source/get-started/cloud-install/aws-web.rst
  source/get-started/cloud-install/azure.rst
  source/get-started/cloud-install/digitalocean.rst
  source/get-started/cloud-install/gce.rst
Labels: P2, new

#958 Update increase-virtual-disk-size doc.
  source/_figures/increase-virtual-disk-size/01-increase-virtual-disk-size-original.png
  source/_figures/increase-virtual-disk-size/01-increase-virtual-disk-size.png
  source/_figures/increase-virtual-disk-size/02-increase-virtual-disk-size-original.png
  source/_figures/increase-virtual-disk-size/02-increase-virtual-disk-size.png
  source/guides/maintenance/figures/increase-virtual-disk-size-1.png
  source/guides/maintenance/figures/increase-virtual-disk-size-2.png
  source/guides/maintenance/increase-virtual-disk-size.rst
Labels: P2

#962 Update for DLRS V5 release
  source/guides/stacks/dlrs.rst
Labels: P1

#939 Update to wifi guide to include wpa_supplicant.
  source/guides/network/wifi.rst
Labels: P2

#909 Add how to boot Clear via GRUB.
  source/tutorials/multi-boot/dual-boot-linux.rst
  source/tutorials/multi-boot/multi-boot.rst
Labels: P2

#965 Update readme URL and remove redundant Seldon section
  source/guides/stacks/dlrs.rst
Labels: P2, bug

#961 cpu-performance.rst: add thermal configuration section
  source/guides/maintenance/cpu-performance.rst
Labels: P2
