Repository clearlinux/clear-linux-documentation, pull requests merged in 2019-06, with the labels that each got.

#526 Removes multi-boot tutorial; deferred until further technical review.
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-01.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-02.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-03.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-04.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-05.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-06.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-07.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-08.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-09.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-10.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-11.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-12.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-mint-1.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-mint-2.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-mint-3.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-mint-4.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-mint-5.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-restore-bl-1.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-restore-bl-2.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-rhel-1.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-rhel-2.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-rhel-3.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-rhel-4.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-rhel-5.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-rhel-6.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-rhel-7.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-sles-1.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-sles-2.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-sles-3.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-sles-4.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-ubuntu-1.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-ubuntu-2.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-ubuntu-3.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-ubuntu-4.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-ubuntu-5.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-win-1.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-win-2.png
  source/clear-linux/tutorials/multi-boot/figures/multi-boot-win-3.png
  source/clear-linux/tutorials/multi-boot/multi-boot-mint.rst
  source/clear-linux/tutorials/multi-boot/multi-boot-restore-bl.rst
  source/clear-linux/tutorials/multi-boot/multi-boot-rhel.rst
  source/clear-linux/tutorials/multi-boot/multi-boot-sles.rst
  source/clear-linux/tutorials/multi-boot/multi-boot-ubuntu.rst
  source/clear-linux/tutorials/multi-boot/multi-boot-win.rst
  source/clear-linux/tutorials/multi-boot/multi-boot.rst
  source/clear-linux/tutorials/tutorials.rst
Labels: P1

#529 Add link to quantization tools for model conversion in DLRS tutorial
  source/clear-linux/tutorials/dlrs/dlrs.rst
Labels: P2, enhancement

#525 Adds redis tutorial with systemctl service check, 2 example use cases
  source/clear-linux/tutorials/redis.rst
  source/clear-linux/tutorials/tutorials.rst
Labels: P2

#530 Replaces `swupd verify` and related flag commands per #522.
  source/clear-linux/concepts/swupd-about.rst
  source/clear-linux/guides/maintenance/fix-broken-install.rst
  source/clear-linux/guides/network/custom-clear-container.rst
  source/clear-linux/guides/tooling/autospec.rst
  source/clear-linux/guides/tooling/swupd-guide.rst
  source/clear-linux/tutorials/kata.rst
  source/clear-linux/tutorials/nvidia.rst
Labels: P1, hot :fire:

#537 Add statement to clarify enable/disable default status of client
  source/clear-linux/concepts/telemetry-about.rst
  source/clear-linux/guides/telemetrics/telem-guide.rst
Labels: CL Forums

#509 TCS review of swupd-guide
  source/clear-linux/guides/tooling/swupd-guide.rst
Labels: P2, editorial :pencil2:

#534 TCS edits in Creating CL VM on Google Cloud Platform doc
  source/clear-linux/get-started/virtual-machine-install/gce.rst
Labels: editorial :pencil2:

#514 KP add proxy tutorial
  source/clear-linux/guides/guides.rst
  source/clear-linux/tutorials/tutorial-proxy.rst
  source/clear-linux/tutorials/tutorials.rst
Labels: P2

#551 Update KVM download script
  source/clear-linux/get-started/virtual-machine-install/kvm.rst
Labels: P1

#549 Update telemetry about
  source/clear-linux/concepts/telemetry-about.rst
Labels: P2

#550 Add section for kubectl to dlrs tutorial
  source/clear-linux/tutorials/dlrs/dlrs.rst
Labels: P2, enhancement
