Repository clearlinux/clear-linux-documentation, pull requests merged in 2019-11, with the labels that each got.

#892 Editorial changes for grammar and formatting.
  source/get-started/virtual-machine-install/virt-manager.rst
Labels: P2, editorial :pencil2:

#897 Correct obsolete URL for contribution guidelines.
  README.rst
Labels: P1

#884 Add dual-boot-linux for CL with other grub-based linux distros.
  source/_figures/multi-boot/dual-boot-linux-01.png
  source/_figures/multi-boot/dual-boot-linux-02.png
  source/_figures/multi-boot/dual-boot-linux-03.png
  source/_figures/multi-boot/dual-boot-linux-04.png
  source/_figures/multi-boot/dual-boot-linux-05.png
  source/_figures/multi-boot/dual-boot-linux-06.png
  source/_figures/multi-boot/dual-boot-linux-07.png
  source/_figures/multi-boot/dual-boot-linux-08.png
  source/_figures/multi-boot/dual-boot-linux-09.png
  source/_figures/multi-boot/dual-boot-linux-10.png
  source/_figures/multi-boot/dual-boot-linux-11.png
  source/_figures/multi-boot/dual-boot-linux-12.png
  source/get-started/bare-metal-install-desktop.rst
  source/tutorials/multi-boot/dual-boot-linux.rst
Labels: P1, new

#899 Removes 1 empty space to assure proper render in dual-boot-linux.
  source/tutorials/multi-boot/dual-boot-linux.rst
Labels: bug

#902 Update dbrs.rst
  source/guides/stacks/dbrs.rst
Labels: P2

#903 Update dbrs.rst
  source/guides/stacks/dbrs.rst
Labels: P2

#893 Update URL for DARS repository
  source/guides/stacks/dars.rst
Labels: P2, enhancement

#920 Update URL for kfctl_k8s_istio.yaml
  source/guides/stacks/dlrs.rst
Labels: P1

#895 Fixed nesting issue.
  source/tutorials/php.rst
Labels: P2, editorial :pencil2:

#925 Revise bullet to clarify offline install option, bare-metal-install-desktop
  source/get-started/bare-metal-install-desktop.rst
Labels: P1

#929 Add guide for Media Reference Stack
  source/_figures/stacks/mers-fig-1.png
  source/_figures/stacks/mers-fig-2.png
  source/guides/stacks/mers.rst
  source/substitutions.txt
  source/tutorials/proxy.rst
Labels: P1, new

#931 Correct ext. GitHub link; correct syntax of int. link to building custom Docker image in mers
  source/guides/stacks/mers.rst
Labels: P1

#932 iPXE updated to use clr-installer.
  source/_figures/ipxe/ipxe-install-1.png
  source/_figures/ipxe/ipxe-install-2.png
  source/get-started/index.rst
  source/get-started/ipxe-install.rst
  source/guides/clear/ister.rst
  source/guides/maintenance/bulk-provision.rst
  source/guides/maintenance/deploy-at-scale.rst
  source/guides/maintenance/figures/bulk-provision-flow.png
  source/guides/network/figures/network-boot-flow.png
  source/guides/network/figures/network-boot-setup.png
  source/guides/network/ipxe-install.rst
Labels: P1

#927 Add instructions for virtualenv in readme; revise make venv target in Makefile
  Makefile
  README.rst
Labels: P2, new

#934 Fixes links that appear to be broken.
  source/get-started/ipxe-install.rst
Labels: P1

#935 Resolve rendering error in README.
  README.rst
Labels: P2

#937 Troubleshooting tip on how to erase LVM partitions
  source/get-started/bare-metal-install-desktop.rst
  source/get-started/bare-metal-install-server.rst
Labels: P2
