Repository clearlinux/clear-linux-documentation, pull requests merged in 2019-10, with the labels that each got.

#851 Revise to allow offline installation in bare-metal-install-desktop and -server
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-04.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-05.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-06.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-07.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-08.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-09.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-10.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-11.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-12.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-13.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-14.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-15.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-16.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-17.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-18.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-19.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-20.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-21.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-22.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-23.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-24.png
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-25.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-15.png
  source/get-started/bare-metal-install-desktop.rst
  source/get-started/bare-metal-install-server.rst
Labels: P2

#853 Remove -version flag from os-install command
  source/guides/maintenance/container-image-new.rst
Labels: P2, bug

#794 Tl telem
  source/guides/clear/telemetrics.rst
Labels: P1

#848 Upleveled Contribution guidelines, edited text.
  source/collaboration/collaboration.rst
  source/collaboration/structure-formatting.rst
  source/collaboration/writing-guide.rst
  source/index.rst
  source/reference/collaboration/collaboration.rst
  source/reference/index.rst
Labels: P2

#852 Adds labels for code blocks used in Clear Linux docs
  source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
Labels: P3, new

#855 Update modify container images document
  source/guides/maintenance/container-image-modify.rst
Labels: P2

#865 Update index.rst
  source/FAQ/index.rst
Labels: hacktoberfest

#867 Add kubectl section for basic use case verification
  source/guides/stacks/dlrs.rst
Labels: P2, enhancement

#850 Update NVIDIA drivers documentation
  source/tutorials/nvidia.rst
Labels: P2

#854 Update compatible version to CL-31130; replace bundles to install in dpdk
  source/guides/network/dpdk.rst
Labels: P2

#863 Add examples for Hadoop and Kubernetes
  source/guides/stacks/dars.rst
Labels: P2, enhancement

#869 Add tutorial for PHP install & config
  source/tutorials/php.rst
  source/tutorials/wordpress/web-server-install.rst
Labels: P2, new

#871 Editorial changes in Hyper-v guide for grammar and formatting.
  source/get-started/virtual-machine-install/hyper-v.rst
Labels: P2, editorial :pencil2:

#874 Move Manage User to Required options; secure root in bare-metal-install-server
  source/_figures/bare-metal-install-server/bare-metal-install-server-18.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-19.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-20.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-21.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-22.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-23.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-24.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-24X.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-25.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-26.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-27.png
  source/get-started/bare-metal-install-server.rst
Labels: P1

#879 Clean up DLRS release section
  source/guides/stacks/dlrs.rst
Labels: P2, enhancement

#885 https://github.com/clearlinux/clear-linux-documentation/issues/857: F…
  README.rst
  source/about.rst
  source/collaboration/structure-formatting.rst
  source/collaboration/writing-guide.rst
  source/get-started/bare-metal-install-server.rst
  source/get-started/compatibility-check.rst
  source/get-started/index.rst
  source/get-started/virtual-machine-install/vmware-esxi-install-cl.rst
  source/get-started/virtual-machine-install/vmware-esxi-preconfigured-cl-image.rst
  source/guides/maintenance/architect-lifecycle.rst
  source/guides/maintenance/resource-limits.rst
  source/guides/network/openssh-server.rst
  source/guides/network/vnc.rst
  source/guides/stacks/dbrs.rst
  source/guides/stacks/dlrs.rst
  source/reference/image-types.rst
  source/tutorials/docker.rst
Labels: P3, community, hacktoberfest

#882 Add Wi-Fi guide
  source/_figures/wifi/nmtui_1.png
  source/_figures/wifi/nmtui_2.png
  source/_figures/wifi/nmtui_3.png
  source/_figures/wifi/nmtui_4.png
  source/_figures/wifi/nmtui_5.png
  source/_figures/wifi/wifi-1.1.png
  source/_figures/wifi/wifi-2.png
  source/_figures/wifi/wifi-3.png
  source/_figures/wifi/wifi-4.png
  source/_figures/wifi/wifi-5.png
  source/guides/network/wifi.rst
Labels: P3
