Repository clearlinux/clear-linux-documentation, pull requests merged in 2019-05, with the labels that each got.

#484 Adds Confirm network connection and Software sections.
  source/clear-linux/get-started/bare-metal-install-desktop/bare-metal-install-desktop.rst
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-02.png
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-03.png
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-04.png
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-05.png
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-06.png
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-07.png
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-08.png
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-09.png
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-10.png
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-11.png
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-12.png
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-13.png
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-14.png
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-15.png
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-16.png
  source/clear-linux/get-started/bare-metal-install-desktop/figures/bare-metal-install-desktop-17.png
Labels: hot

#486 Add DARS v1 tutorial
  source/clear-linux/tutorials/dars.rst
  source/clear-linux/tutorials/tutorials.rst
Labels: hot

#488 dars: Revise title and all internal refs to Data Analytics Ref Stack.
  source/clear-linux/tutorials/dars.rst
Labels: hot

#487 Revises Create a bootable USB drive on Windows, Rufus upgrade to 3.5
  source/clear-linux/get-started/bootable-usb/bootable-usb.rst
  source/clear-linux/get-started/bootable-usb/figures/bootable-usb-mac-01.png
  source/clear-linux/get-started/bootable-usb/figures/bootable-usb-windows-02.png
  source/clear-linux/get-started/bootable-usb/figures/bootable-usb-windows-03.png
  source/clear-linux/get-started/bootable-usb/figures/bootable-usb-windows-1.png
  source/clear-linux/get-started/bootable-usb/figures/bootable-usb-windows-2.png
  source/clear-linux/get-started/bootable-usb/figures/bootable-usb-windows-3.png
Labels: hot

#490 Completed TCS editorial review
  source/clear-linux/tutorials/dlrs/dlrs.rst
Labels: editorial

#494 Add introductory text and link to benchmark results
  source/clear-linux/tutorials/dars.rst
Labels: enhancement

#454 Completed TCS editorial review
  source/clear-linux/guides/maintenance/kernel-modules-dkms.rst
  source/clear-linux/guides/maintenance/kernel-modules.rst
Labels: editorial

#506 Removes mixin.rst and all references to it.
  source/clear-linux/concepts/autospec-about.rst
  source/clear-linux/concepts/mixer-about.rst
  source/clear-linux/guides/deploy-at-scale.rst
  source/clear-linux/guides/guides.rst
  source/clear-linux/guides/tooling/autospec.rst
  source/clear-linux/guides/tooling/mixer.rst
  source/clear-linux/guides/tooling/mixin.rst
Labels: hot

#502 virtualbox-cl-installer: Revise figures to match VirtualBox 6.0.8 and new live-server installer.
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-cl-first-login.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-cl-remove-non-lts-kernels.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-convert-raw-to-VDI.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-create-disk.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-create-vm-choose-disk.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-create-vm-existing-disk.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-create-vm-new-disk.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-create-vm-no-disk.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-extract-cl-IMG.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-extract-cl-ISO.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-new-vm.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-shutdown-vm.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-start-vm.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-vm-created.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-vm-insert-ga-cd.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-vm-settings-EFI.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-vm-settings-browse-ISO.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-vm-settings-mount-ISO.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/vbox-vm-settings-unmount-ISO.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/virtualbox-cl-installer-01.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/virtualbox-cl-installer-02.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/virtualbox-cl-installer-03.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/virtualbox-cl-installer-04.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/virtualbox-cl-installer-05.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/virtualbox-cl-installer-06.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/virtualbox-cl-installer-07.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/virtualbox-cl-installer-08.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/virtualbox-cl-installer-09.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/virtualbox-cl-installer-10.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/virtualbox-cl-installer-11.png
  source/clear-linux/get-started/virtual-machine-install/figures/vbox/virtualbox-cl-installer-12.png
  source/clear-linux/get-started/virtual-machine-install/virtual-machine-install.rst
  source/clear-linux/get-started/virtual-machine-install/virtualbox-cl-installer.rst
  source/clear-linux/get-started/virtual-machine-install/virtualbox.rst
  source/clear-linux/reference/compatible-kernels.rst
  source/substitutions.txt
Labels: hot :fire:
