Repository clearlinux/clear-linux-documentation, pull requests merged in 2020-03, with the labels that each got.

#1054 Update kata doc after default runtime change
  source/tutorials/kata.rst
Labels: P2

#1060 Correct filenames
  source/tutorials/nvidia-cuda.rst
Labels: P1, community

#1062 Update FAQ
  source/FAQ/index.rst
Labels: P2, forum

#1051 Add container images to get-started page
  source/get-started/containers/container-images.rst
  source/get-started/index.rst
Labels: P2, new

#1064 Makes driver find application profiles
  source/tutorials/nvidia.rst
Labels: P2, community

#1061 Adds hugepages config guide to explain defaults and config settings
  source/guides/maintenance/configure-hugepages.rst
Labels: P2, new

#1068 nvidia.rst: Add a section to restore ld.so.conf
  source/tutorials/nvidia.rst
Labels: P2

#1066 Update instructions for X11 forwarding and SFTP
  source/guides/network/openssh-server.rst
Labels: P2

#1070 nvidia.rst: Remove `chmod +x` on installer
  source/tutorials/nvidia.rst
Labels: P2

#1067 Added fix for swupd bundle-add Error
  source/guides/stacks/dlrs.rst
Labels: P2

#1072 Import Clear AWS image, create AMI, and launch.
  source/_figures/aws/import-clr-aws-01.png
  source/_figures/aws/import-clr-aws-02.png
  source/_figures/aws/import-clr-aws-03.png
  source/_figures/aws/import-clr-aws-04.png
  source/_figures/aws/import-clr-aws-05.png
  source/_figures/aws/import-clr-aws-06.png
  source/_figures/aws/import-clr-aws-07.png
  source/_figures/aws/import-clr-aws-08.png
  source/_figures/aws/import-clr-aws-09.png
  source/_figures/aws/import-clr-aws-10.png
  source/_figures/aws/import-clr-aws-11.png
  source/_figures/aws/import-clr-aws-12.png
  source/_figures/aws/import-clr-aws-13.png
  source/_figures/aws/import-clr-aws-14.png
  source/_figures/aws/import-clr-aws-15.png
  source/_figures/aws/import-clr-aws-16.png
  source/_figures/aws/import-clr-aws-17.png
  source/_figures/aws/import-clr-aws-18.png
  source/_figures/aws/import-clr-aws-19.png
  source/_figures/aws/import-clr-aws-20.png
  source/_figures/aws/import-clr-aws-21.png
  source/_figures/aws/import-clr-aws-22.png
  source/_figures/aws/import-clr-aws-23.png
  source/_figures/aws/import-clr-aws-24.png
  source/_figures/aws/import-clr-aws-25.png
  source/_figures/aws/import-clr-aws-26.png
  source/_figures/aws/import-clr-aws-27.png
  source/_figures/aws/import-clr-aws-28.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-01-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-02-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-03-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-04-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-05-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-06-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-07-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-08-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-09-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-10-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-11-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-12-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-13-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-14-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-15-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-16-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-17-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-18-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-19-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-20-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-21-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-22-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-23-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-24-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-25-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-26-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-27-original.png
  source/_figures/aws/import-clr-aws-originals/import-clr-aws-28-original.png
  source/get-started/cloud-install/import-clr-aws.rst
Labels: P2

#1079 Update unattended installation doc and deprecate ister doc.
  source/get-started/install-configfile.rst
  source/guides/clear/ister.rst
  source/guides/clear/mixer.rst
Labels: P2

#1081 Add memcached instructions for v2.0
  source/guides/stacks/dbrs.rst
Labels: P2, enhancement

#1075 Create, Install, and Manage 3rd-party Bundles
  source/guides/clear/mixer.rst
  source/guides/clear/swupd-3rd-party.rst
Labels: P1

#1088 Fix broken link
  source/guides/stacks/dbrs.rst
Labels: P1

#1092 Add path to kernel source headers
  source/guides/kernel/kernel-modules-dkms.rst
  source/guides/kernel/kernel-modules.rst
Labels: P2

#1097 Replace Fig. 32 to update URL for swupd in bare-metal-install-server
  source/_figures/bare-metal-install-server/bare-metal-install-server-32.png
  source/get-started/bare-metal-install-server.rst
Labels: P1

#1050 Adds section on bundle definition file and removes Docker refs in mixer
  source/guides/clear/mixer.rst
Labels: P2
