Repository clearlinux/clear-linux-documentation, pull requests merged in 2020-02, with the labels that each got.

#1010 Update Clear on VMware Workstation player.
  source/_figures/vmw-player/vmw-player-01.png
  source/_figures/vmw-player/vmw-player-01.png.original
  source/_figures/vmw-player/vmw-player-02.png
  source/_figures/vmw-player/vmw-player-02.png.original
  source/_figures/vmw-player/vmw-player-03.png
  source/_figures/vmw-player/vmw-player-03.png.original
  source/_figures/vmw-player/vmw-player-04.png
  source/_figures/vmw-player/vmw-player-04.png.original
  source/_figures/vmw-player/vmw-player-05.png
  source/_figures/vmw-player/vmw-player-05.png.original
  source/_figures/vmw-player/vmw-player-06.png
  source/_figures/vmw-player/vmw-player-06.png.original
  source/_figures/vmw-player/vmw-player-07.png
  source/_figures/vmw-player/vmw-player-07.png.original
  source/_figures/vmw-player/vmw-player-08.png
  source/_figures/vmw-player/vmw-player-08.png.original
  source/_figures/vmw-player/vmw-player-09.png
  source/_figures/vmw-player/vmw-player-09.png.original
  source/_figures/vmw-player/vmw-player-10.png
  source/_figures/vmw-player/vmw-player-10.png.original
  source/_figures/vmw-player/vmw-player-11.png
  source/_figures/vmw-player/vmw-player-11.png.original
  source/_figures/vmw-player/vmw-player-12.png
  source/_figures/vmw-player/vmw-player-12.png.original
  source/_figures/vmw-player/vmw-player-13.png
  source/_figures/vmw-player/vmw-player-13.png.original
  source/_figures/vmw-player/vmw-player-14.png
  source/_figures/vmw-player/vmw-player-14.png.original
  source/_figures/vmw-player/vmw-player-15.png
  source/_figures/vmw-player/vmw-player-15.png.original
  source/_figures/vmw-player/vmw-player-16.png
  source/_figures/vmw-player/vmw-player-16.png.original
  source/_figures/vmw-player/vmw-player-preconf-01.png
  source/_figures/vmw-player/vmw-player-preconf-02.png
  source/_figures/vmw-player/vmw-player-preconf-03.png
  source/_figures/vmw-player/vmw-player-preconf-04.png
  source/_figures/vmw-player/vmw-player-preconf-05.png
  source/_figures/vmw-player/vmw-player-preconf-06.png
  source/_figures/vmw-player/vmw-player-preconf-07.png
  source/_figures/vmw-player/vmw-player-preconf-08.png
  source/_figures/vmw-player/vmw-player-preconf-09.png
  source/_figures/vmw-player/vmw-player-preconf-12.png
  source/_figures/vmw-player/vmw-player-preconf-13.png
  source/_figures/vmw-player/vmw-player-preconf-14.png
  source/_figures/vmw-player/vmw-player-preconf-15.png
  source/_figures/vmw-player/vmw-player-preconf-16.png
  source/get-started/bare-metal-install-desktop.rst
  source/get-started/bare-metal-install-server.rst
  source/get-started/virtual-machine-install/vmw-player.rst
Labels: P2

#1020 Fix missing backslashes for Windows path in vmw-player
  source/get-started/virtual-machine-install/vmw-player.rst
Labels: P1

#1015 Update mixer build image to use clr-installer.
  source/guides/clear/mixer.rst
Labels: P1

#1013 Updated time.rst
  source/guides/network/time.rst
Labels: P3

#1016 Update NVIDIA drivers document with known issues and workarounds
  source/_figures/nvidia/nvidia-gnome-crash.png
  source/tutorials/nvidia.rst
Labels: P2

#1025 Fix typo: s/bundle <search term>/search <term>/
  source/guides/clear/swupd.rst
Labels: P1

#1024 update to current settings
  source/tutorials/nvidia-cuda.rst
Labels: P2, community

#1023 Add OpenFaaS tutorial
  source/_figures/openfaas/openfaas-function-output.png
  source/_figures/openfaas/openfaas-invoke-function.png
  source/_figures/openfaas/openfaas-login.png
  source/tutorials/openfaas.rst
Labels: P2, new

#1036 Updates based on native Chinese speaker review.
  source/get-started/cloud-install/qingcloud.rst
Labels: P2

#1034 Update NVIDIA tutorial to recommend LTS kernel
  source/tutorials/nvidia.rst
Labels: P3

#1040 Revises telemetry figure to correct URL; reorders steps.
  source/_figures/bare-metal-install-server/bare-metal-install-server-22.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-28.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-29.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-30.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-31.png
  source/get-started/bare-metal-install-server.rst
Labels: P1

#1035 Revise steps for clarity and dist UI components, bootable-usb.
  source/_figures/bootable-usb/balenaEtcher_Done.PNG
  source/_figures/bootable-usb/balenaEtcher_DriveSlect.PNG
  source/_figures/bootable-usb/balenaEtcher_Flashing.PNG
  source/_figures/bootable-usb/balenaEtcher_ImageSelect.PNG
  source/_figures/bootable-usb/balenaEtcher_ImgaeSlect.PNG
  source/_figures/bootable-usb/balenaEtcher_ReadyToFlash.PNG
  source/_figures/bootable-usb/balenaEtcher_Start.PNG
  source/_figures/bootable-usb/balenaEtcher_StartingToFlash.PNG
  source/get-started/bootable-usb.rst
Labels: P2

#1037 Update to CPU performance guide.
  source/_figures/cpu-perf-guide/dptf_bios.png
  source/guides/maintenance/cpu-performance.rst
Labels: P2

#1046 Sets max width of content to 1100 pixels
  source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
Labels: P2

#1055 Add Horovod and OpenMPI section, closes #1041
  source/guides/stacks/dlrs.rst
Labels: P1, hot :fire:

#1057 Adds ticks, File System descriptors, Default part schema, bare-metal-install-desktop
  source/get-started/bare-metal-install-desktop.rst
Labels: P2, editorial :pencil2:

#1053 Add missing mkdir command in nvidia doc
  source/tutorials/nvidia.rst
Labels: P1
