Repository clearlinux/clear-linux-documentation, pull requests merged in 2020-06, with the labels that each got.

#1184 Update TM&B in Get Started section of docs
  source/get-started/virtual-machine-install/hyper-v.rst
  source/get-started/virtual-machine-install/kvm.rst
  source/get-started/virtual-machine-install/virt-manager.rst
  source/get-started/virtual-machine-install/virtualbox-cl-installer.rst
  source/get-started/virtual-machine-install/vmw-player.rst
Labels: P2

#1182 Update TM&B in About section of docs
  source/about.rst
Labels: P2

#1180 Implements copy button
  make.bat
  requirements.txt
  source/Makefile
  source/_scripts/js/copybutton.js
  source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
  source/conf.py
  source/guides/kernel/kernel-modules-dkms.rst
Labels: P3, new

#1181 Update TM&B in Reference section of docs
  source/reference/compatible-hardware.rst
  source/reference/system-requirements.rst
Labels: P2

#1183 Update compatibility-check
  source/get-started/compatibility-check.rst
Labels: P2

#1186 Align bare-metal-install-* docs with clr-installer verify-iso-integrity
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-01.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-01.png
  source/get-started/bare-metal-install-desktop.rst
  source/get-started/bare-metal-install-server.rst
Labels: P1

#1188 Removes error message re "Missing CLR_SWAP partition"
  source/_figures/multi-boot/dual-boot-linux-02.png
Labels: P3

#1189 Adds reference in bare-metal-install-* to use YAML config file to install
  source/get-started/bare-metal-install-desktop.rst
  source/get-started/bare-metal-install-server.rst
Labels: P3

#1174 peteonrails/add zfs tutorial
  source/tutorials/index.rst
  source/tutorials/zfs.rst
Labels: P3, community

#1197 Update FAQ ZFS question with link to tutorial
  source/FAQ/index.rst
Labels: P2

#1196 Update vnc.rst
  source/guides/network/vnc.rst
Labels: P1
