Repository clearlinux/clear-linux-documentation, pull requests merged in 2020-05, with the labels that each got.

#1110 Adds manpages to reference section of Clear Linux docs
  .github/workflows/check.yml
  .github/workflows/main.yml
  .github/workflows/publish.yml
  .gitignore
  Makefile
  README.rst
  make.bat
  source/Makefile
  source/_scripts/_python/manpages/Makefile
  source/_scripts/_python/manpages/man.bat
  source/_scripts/_python/manpages/manpages.py
  source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
  source/conf.py
  source/reference/index.rst
Labels: P2, new

#1148 Remove older figure 3 screenshot, inapplicable to Gen 1 Hyper-V.
  source/get-started/virtual-machine-install/figures/hyper-v/hyper-v-03-old.png
Labels: P3

#1152 Update list of display managers on about page
  source/about.rst
Labels: P2

#1151 Add tri-weekly check of links
  .github/workflows/linkcheck.yml
Labels: P2

#1121 Simple HPC tutorial
  source/_figures/hpc/hpc-01.png
  source/tutorials/hpc.rst
Labels: P1, new

#1149 Performance doc
  source/guides/clear/performance.rst
Labels: P1

#1156 Update SMB server tutorial
  source/_figures/samba/smb-1.png
  source/_figures/samba/smb-2.png
  source/_figures/samba/smb-server-01.png
  source/_figures/samba/smb-server-02.png
  source/tutorials/smb-server.rst
  source/tutorials/smb.rst
Labels: P2, new

#1162 Escapes local host link, so it isn't turned into active link.
  source/guides/stacks/dlrs.rst
Labels: P2

#1163 Update MeRS page for V2 release
  source/guides/stacks/mers.rst
Labels: P1

#1154 Update WordPress tutorial
  source/tutorials/lamp-server.rst
  source/tutorials/php.rst
  source/tutorials/wordpress.rst
  source/tutorials/wordpress/wp-install.rst
Labels: P3

#1161 Update Redis tutorial
  source/tutorials/redis.rst
Labels: P3

#1143 Cool columns of tutorials sorted by experience level.
  source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
  source/tutorials/index.rst
Labels: P2, new

#1144 Adds rationale for tutorial difficulty ratings
  source/_figures/reference/tutorial-ratings-01.png
  source/collaboration/collaboration.rst
  source/reference/index.rst
  source/reference/tutorial-ratings.rst
  source/tutorials/index.rst
Labels: P2, new

#1117 Add reDocs GUI support
  .gitignore
  make.bat
  setup.py
  source/_scripts/_python/manpages/manpages.py
  source/conf.py
  tox.ini
Labels: P2

#1153 Tutorial: Create a mirror of upstream update server
  source/_figures/mirror-upstream-server/mirror-upstream-server-01.png
  source/_figures/mirror-upstream-server/mirror-upstream-server-02.png
  source/tutorials/mirror-upstream-server.rst
Labels: P2

#1170 Revise tutorial index to Low, Moderate, Difficult per CL meeting.
  source/tutorials/index.rst
Labels: P1

#1177 Deprecate OpenVINO tutorial; CL no longer supports computer-vision-openvino
  source/guides/maintenance/developer-workstation.rst
  source/tutorials/index.rst
  source/tutorials/openvino.rst
Labels: P1

#1173 Add 3 tutorials to tutorials index for discoverability.
  source/tutorials/index.rst
Labels: P2

#1165 Update "Proxy Configuration" tutorial
  source/guides/clear/autospec.rst
  source/guides/clear/mixer.rst
  source/guides/network/proxy.rst
  source/tutorials/proxy.rst
Labels: P2

#1176 Revises tutorial ratings flowchart for logical coherence.
  source/_figures/reference/tutorial-ratings-01.png
  source/_figures/reference/tutorial-ratings-01.svg
  source/reference/tutorial-ratings.rst
Labels: P2
