Repository clearlinux/clear-linux-documentation, pull requests merged in 2020-01, with the labels that each got.

#975 Update landing page
  source/_themes/otc_tcs_sphinx_theme/layout.html
  source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
  source/conf.py
  source/index.rst
Labels: P2, new

#976 doc: refresh the Clear Linux OS on GCP guide
  source/_figures/gce/02-storage-browser.png
  source/_figures/gce/03-create-bucket.png
  source/_figures/gce/30-create-vm.png
  source/_figures/gce/30-vm-none.png
  source/get-started/cloud-install/gce.rst
Labels: P2

#977 Adds support for drop shadows on figures
  source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
Labels: P3, new

#980 Add document for Broadcom drivers
  source/guides/kernel/firmware.rst
  source/tutorials/broadcom.rst
Labels: P2, new

#981 Alternative - install Windows after Clear Linux
  source/_figures/digitalocean/Thumbs.db
  source/_figures/increase-virtual-disk-size/Thumbs.db
  source/_figures/multi-boot/Thumbs.db
  source/_figures/multi-boot/dual-boot-win-01-original.png
  source/_figures/multi-boot/dual-boot-win-01.png
  source/_figures/multi-boot/dual-boot-win-02-original.png
  source/_figures/multi-boot/dual-boot-win-02.png
  source/_figures/multi-boot/dual-boot-win-03.png
  source/_figures/multi-boot/dual-boot-win-06-original.png
  source/_figures/multi-boot/dual-boot-win-06.png
  source/_figures/multi-boot/dual-boot-win-07-original.png
  source/_figures/multi-boot/dual-boot-win-07.png
  source/_figures/multi-boot/dual-boot-win-08-original.png
  source/_figures/multi-boot/dual-boot-win-08.png
  source/tutorials/multi-boot/dual-boot-win.rst
Labels: P2

#982 Revise `dd` command to clarify and avoid misinterpretation in bootable-usb.
  source/get-started/bootable-usb.rst
Labels: P2

#877 Add inference and multinode guide page for DLRS stack
  source/_figures/stacks/Locust_charts.png
  source/_figures/stacks/Locust_exception.png
  source/_figures/stacks/Locust_failures.png
  source/_figures/stacks/Locust_statistics.png
  source/_figures/stacks/htop.png
  source/_figures/stacks/kubeflow-seldon-dlrs-example-diagram.png
  source/guides/stacks/dlrs-inference.rst
Labels: P2, new

#924 New VMware Workstation tutorial
  source/tutorials/vmware-workstation.rst
Labels: P2, new

#990 Fix minor text/formatting errors in DKMS kernel module guide.
  source/guides/kernel/kernel-modules-dkms.rst
Labels: P3

#996 Clear Linux on Proxmox hypervisor.
  source/_figures/proxmox/proxmox-01-original.png
  source/_figures/proxmox/proxmox-01.png
  source/_figures/proxmox/proxmox-02-original.png
  source/_figures/proxmox/proxmox-02.png
  source/_figures/proxmox/proxmox-03-original.png
  source/_figures/proxmox/proxmox-03.png
  source/_figures/proxmox/proxmox-04-original.png
  source/_figures/proxmox/proxmox-04.png
  source/_figures/proxmox/proxmox-05-original.png
  source/_figures/proxmox/proxmox-05.png
  source/_figures/proxmox/proxmox-06-original.png
  source/_figures/proxmox/proxmox-06.png
  source/_figures/proxmox/proxmox-07-original.png
  source/_figures/proxmox/proxmox-07.png
  source/_figures/proxmox/proxmox-08-original.png
  source/_figures/proxmox/proxmox-08.png
  source/_figures/proxmox/proxmox-09-original.png
  source/_figures/proxmox/proxmox-09.png
  source/_figures/proxmox/proxmox-10-original.png
  source/_figures/proxmox/proxmox-10.png
  source/_figures/proxmox/proxmox-11-original.png
  source/_figures/proxmox/proxmox-11.png
  source/_figures/proxmox/proxmox-12-original.png
  source/_figures/proxmox/proxmox-12.png
  source/_figures/proxmox/proxmox-13-original.png
  source/_figures/proxmox/proxmox-13.png
  source/get-started/virtual-machine-install/proxmox.rst
Labels: P2, new

#971 Qing cloud
  source/_figures/qingcloud/QingCloud-1.png
  source/_figures/qingcloud/QingCloud-10.png
  source/_figures/qingcloud/QingCloud-11.png
  source/_figures/qingcloud/QingCloud-12.png
  source/_figures/qingcloud/QingCloud-13.png
  source/_figures/qingcloud/QingCloud-14.png
  source/_figures/qingcloud/QingCloud-15.png
  source/_figures/qingcloud/QingCloud-16.png
  source/_figures/qingcloud/QingCloud-17.png
  source/_figures/qingcloud/QingCloud-18.png
  source/_figures/qingcloud/QingCloud-19.png
  source/_figures/qingcloud/QingCloud-2.png
  source/_figures/qingcloud/QingCloud-20.png
  source/_figures/qingcloud/QingCloud-21.png
  source/_figures/qingcloud/QingCloud-3.png
  source/_figures/qingcloud/QingCloud-4.png
  source/_figures/qingcloud/QingCloud-5.png
  source/_figures/qingcloud/QingCloud-6.png
  source/_figures/qingcloud/QingCloud-7.png
  source/_figures/qingcloud/QingCloud-8.png
  source/_figures/qingcloud/QingCloud-9.png
  source/get-started/cloud-install/qingcloud.rst
Labels: P3, new

#1000 Update lsblk commands to make it easier to identify devices.
  source/get-started/bootable-usb.rst
  source/guides/maintenance/fix-broken-install.rst
  source/tutorials/multi-boot/dual-boot-win.rst
Labels: P2

#1004 Add min. required disk space for bare-metal-install-desktop and bare-metal-install-server
  source/get-started/bare-metal-install-desktop.rst
  source/get-started/bare-metal-install-server.rst
  source/reference/system-requirements.rst
Labels: P2

#1012 Fix links caught in weekly automated check.
  source/guides/stacks/dbrs.rst
  source/tutorials/redis.rst
Labels: P2

#1007 Minor edit to mixer guide for clarity
  source/guides/clear/mixer.rst
Labels: P3
