Repository clearlinux/clear-linux-documentation, pull requests merged in 2020-04, with the labels that each got.

#1105 Add caution admonition to introduce option to skip-validation-size in sys-reqs.
  source/reference/system-requirements.rst
Labels: P1

#1104 Align bare-metal-install-server and -desktop docs with clr-installer release 2.4.3
  source/_figures/bare-metal-install-desktop/bare-metal-install-desktop-21.png
  source/_figures/bare-metal-install-server/bare-metal-install-server-30.png
Labels: P2

#1111 Update DLRS tutorial with instructions for using Transformers
  source/_figures/stacks/dlrs-transformers-1.png
  source/guides/stacks/dlrs.rst
Labels: enhancement

#1114 Capture kernel boot messages in journal.
  source/guides/kernel/kernel-boot-msg.rst
Labels: P2

#1112 update transformers section
  source/guides/stacks/dlrs.rst
Labels: P2

#1115 Update png in DLRS guide
  source/_figures/stacks/dlrs-transformers-1.png
Labels: P2

#1109 Provide overview of CL architecture, including rationale.
  source/FAQ/index.rst
  source/about.rst
Labels: P2, new

#1127 Update fix broken installation
  source/guides/maintenance/fix-broken-install.rst
Labels: P1

#1120 Add HPCRS guide to Stacks guides.
  source/guides/stacks/hpcrs.rst
Labels: P1, new

#1124 Update bare-metal-install* to use swapfile instead of swap partition
  source/get-started/bare-metal-install-desktop.rst
  source/get-started/bare-metal-install-server.rst
Labels: P2

#1130 nvidia.rst: Added a section on slow boot times
  source/tutorials/nvidia.rst
Labels: P2, community

#1123 Update DLRS guide for v6 release
  source/guides/stacks/dlrs.rst
Labels: P2, enhancement

#1137 Update DLRS guide with correct V6 link
  source/guides/stacks/dlrs.rst
Labels: P1

#1140 Update copyright to be consistent with clearlinux.org.
  source/conf.py
Labels: P3

#1030 Revise kubernetes documentation
  source/tutorials/kubernetes.rst
Labels: P1

#1145 Align with DevOps to change name from azure.vhd to azure-hyperv.vhd.
  source/get-started/virtual-machine-install/figures/hyper-v/hyper-v-03-old.png
  source/get-started/virtual-machine-install/figures/hyper-v/hyper-v-03.png
  source/get-started/virtual-machine-install/hyper-v.rst
  source/guides/clear/compatible-kernels.rst
  source/reference/image-types.rst
Labels: P1
